import { z } from "zod";

export const AnnouncementItem = z.object({
  PK: z.string(),                         
  // Partition Key: "CLASS#<classId>"

  SK: z.string(),                         
  // Sort Key: "ANNOUNCEMENT#<createdAtIso>#<announcementId>"
  // Example: "ANNOUNCEMENT#2025-08-26T18:45:11.022Z#ann_9f23bc1d"

  announcementId: z.string(),             // UUID generated by backend
  classId: z.string(),
  createdAt: z.string(),                  // ISO timestamp
  authorId: z.string(),                   // teacherId (from Cognito sub)
  kind: z.enum(["teacher", "system"]).default("teacher"),
  pinned: z.boolean().default(false),

  files: z.array(
    z.object({
      role: z.enum(["body", "attachment"]),
      key: z.string(),       // S3 object key (e.g. announcements/class/cls_123/ann_9f23bc1d/body.md)
      filename: z.string(),  // original filename
      contentType: z.string()
    })
  )
});

export type AnnouncementItem = z.infer<typeof AnnouncementItem>;

// Example 
// {
//   "PK": "CLASS#cls_123",
//   "SK": "ANNOUNCEMENT#2025-08-26T18:45:11.022Z#ann_9f23bc1d",
//   "announcementId": "ann_9f23bc1d",
//   "classId": "cls_123",
//   "createdAt": "2025-08-26T18:45:11.022Z",
//   "authorId": "usr_456",
//   "kind": "teacher",
//   "pinned": false,
//   "files": [
//     {
//       "role": "body",
//       "key": "announcements/class/cls_123/ann_9f23bc1d/body.md",
//       "filename": "announcement.md",
//       "contentType": "text/markdown"
//     },
//     {
//       "role": "attachment",
//       "key": "announcements/class/cls_123/ann_9f23bc1d/files/lab-guide.pdf",
//       "filename": "lab-guide.pdf",
//       "contentType": "application/pdf"
//     }
//   ]
// }
